

const {
    PROD_PORT,
    PROD_CLOUDINARY_NAME,
PROD_CLOUDINARY_API_KEY,
PROD_CLOUDINARY_API_SECRET
} = process.env

console.log('Running in production mode')

export default {
    PORT: PROD_PORT,
    CLOUDINARY_NAME: PROD_CLOUDINARY_NAME,
    CLOUDINARY_API_KEY: PROD_CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET: PROD_CLOUDINARY_API_SECRET
}